### ISSUE TITLE
React: Two requests to fief - one with error

### ISSUE THREAD

**Issue by michaldev** [fief-dev/fief-js#5]
Hi. I have a bug with library in react.

<img width="524" alt="Zrzut ekranu 2022-12-20 o 23 19 48" src="https://user-images.githubusercontent.com/5132385/208777871-b4dc0c8d-b379-4365-a512-313b22653e8b.png">

I have two requests for fief. First one with status 200, and second one with code 400 (error: "invalid_client"). I receive correctly token, which works very well with fastapi server. Routing works with permissions too. 

<img width="541" alt="Zrzut ekranu 2022-12-20 o 23 20 11" src="https://user-images.githubusercontent.com/5132385/208778094-80382e9e-a310-4cf2-8fd6-8abc78ef4a25.png">

I have default config/method of integration from your docs.

**Comment by michaldev** [comment]
Ok, the problem is probably in strict mode. I'll check tommorow.

**Comment by frankie567** [comment]
Yes, that's something that was identified by another user: https://github.com/orgs/fief-dev/discussions/92#discussioncomment-3832167

I'm not really sure how to avoid this in the library 🤔

**Comment by frankie567** [comment]
So, almost a year later (😅), I got the idea to solve this! It'll be part of the next release :)
