### ISSUE TITLE
Using `redirectToLogin` on an unknown workspace silently fail

### ISSUE THREAD

**Issue by tito** [fief-dev/fief-js#7]
## Describe the bug

If you use `fiefAuth.redirectToLogin(...)`, and the workspace cannot be found, you'll have
- `getOpenIDConfiguration()` receive an error HTTP 400 with content `{"detail":"CANT_DETERMINE_VALID_WORKSPACE"}`
- no error throw, and the `authorizationEndpoint` will be `undefined`

End result is, in your app, you end up with redirecting with an url like `http://.../undefined?response_type=code&client_id=....`
And no clue why :)

## To Reproduce

1. Start empty instance of fief
2. Run your code on this instance
3. See error

## Configuration

* JavaScript environment: VueJS
* Fief client version: 0.13.3

**Comment by frankie567** [comment]
Good catch, @tito, thanks 🙏 

I've added proper error handling for this in [`0.13.5`](https://github.com/fief-dev/fief-js/releases/tag/v0.13.5). You can look for `FiefRequestError` for those cases.
